// Auto-generated MAVLink enums
// DO NOT EDIT MANUALLY

pub const ICAROUS_TRACK_BAND_TYPES = enum(u8) {
    ICAROUS_TRACK_BAND_TYPE_NONE = 0,
    ICAROUS_TRACK_BAND_TYPE_NEAR = 1,
    ICAROUS_TRACK_BAND_TYPE_RECOVERY = 2,
};

pub const ICAROUS_FMS_STATE = enum(u8) {
    ICAROUS_FMS_STATE_IDLE = 0,
    ICAROUS_FMS_STATE_TAKEOFF = 1,
    ICAROUS_FMS_STATE_CLIMB = 2,
    ICAROUS_FMS_STATE_CRUISE = 3,
    ICAROUS_FMS_STATE_APPROACH = 4,
    ICAROUS_FMS_STATE_LAND = 5,
};

pub const MAV_CMD = enum(u16) {
};

