name: build mavlink-zig

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "README.md"
      - "**.md"
      - "LICENSE**"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "README.md"
      - "**.md"
      - "LICENSE**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.0

    - name: Run tests
      run: zig build test --summary all

    - name: Build all
      run: zig build --summary all
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-${{ matrix.os }}
        path: |
          zig-out/bin
          zig-out/lib 
  build-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
            version: 0.14.0
      - name: Build docs
        if: github.ref == 'refs/heads/master'
        run: zig build docs
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/docs

  publish-docs:
    needs: [build-docs]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4