name: Update MAVLink Dialects

on:
  schedule:
    - cron: '4 5 * * *'
  workflow_dispatch:

jobs:
  update-dialects:
    runs-on: ubuntu-22.04

    steps:
    - name: Install Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.0

    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Update submodules to latest
      run: |
        git submodule update --remote --recursive

    - name: Generate Dialects
      run: zig build genv2

    - name: Commit and Push Changes
      run: |
        SUBMODULES=$(git submodule status | awk '{print $2 ": " $1}' | paste -sd ', ' -)
        git add .
        git submodule foreach 'git add $name'
        if ! git diff --cached --quiet; then
          git config user.name mavlink-zig-bot
          git config user.email bot@mavlink-zig.neels.dev
          git commit -m "(automatic) update dialects and submodules to: ${SUBMODULES}"
          git push
        else
          echo "No changes to commit."
        fi

