name: Update MAVLink Dialects

on:
  schedule:
    - cron: "4 5 * * *"
  workflow_dispatch:

jobs:
  update-dialects:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0
          use-cache: false

      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4

      - name: Update mavlink xml commit
        id: update-mavlink-hash
        run: |
          OUTPUT=$(zig fetch --save=mavlink_defs git+https://github.com/mavlink/mavlink 2>&1)
          echo "$OUTPUT"
          HASH=$(echo "$OUTPUT" | grep -oE '[0-9a-f]{40}')
          echo "commit_hash=$HASH" >> "$GITHUB_OUTPUT"

      - name: Generate Dialects
        run: zig build genv2

      - name: Run tests
        run: zig build test --summary all

      - name: Build all
        run: zig build --summary all

      - name: Commit and Push Changes
        run: |
          git config user.name mavlink-zig-bot
          git config user.email bot@mavlink-zig.neels.dev

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "(automatic) Update MAVLink XML Dialects to commit: ${{ steps.update-mavlink-hash.outputs.commit_hash }}"
            git push
          fi
